### ISSUE TITLE
[Task] 팔로우 전역 상태 추가

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#108]
### TODO
1. [x] action, reducer 추가
2. [x] 로그인 시 팔로우 받아와서 저장
3. [x] FollowBtn에서 변경 dispatch, mypage에서 조회
