### ISSUE TITLE
[Task] achievement 뱃지 기능 추가 1

### ISSUE THREAD

**Issue by soominna** [codestates/studeaming#116]
### TODO
1. [x] db 스키마 변경, 새 모델 생성 (achievement, user_achievement)
2. [x] API 경로 추가, 컨트롤러 함수 작성
3. [x] 뱃지 획득 조건을 달성하면 획득 여부를 검사해서 업데이트하는 함수 작성
4. [ ] 달성 조건을 업데이트하는 각각의 컨트롤러들에서 함수 불러오기
