### ISSUE TITLE
[Task] Badge 추가기능

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#123]
### TODO
1. [ ] overflow scroll 설정된 상태에서 오른쪽 버튼 눌렀을 때 가려진 나머지 보여주기
2. [ ] 또는, 아래 -> scroll 이라고 표기하기
3. [ ] UserProfile - BadgeContainer
4. [ ] Sidebar - BadgeContainer
5. [x] 호버시 정보 나타내기
<img width="300" alt="스크린샷 2021-11-30 오후 1 15 35" src="https://user-images.githubusercontent.com/85829962/143984739-e6d77a91-fd9f-4578-8e6c-d044ff48c6f4.png">
<img width="300" alt="스크린샷 2021-11-30 오후 1 23 55" src="https://user-images.githubusercontent.com/85829962/143985369-924d69e9-3725-427c-908e-8a70775e1b93.png">
