### ISSUE TITLE
[Task] SideLog 애니메이션, 반응형

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#153]
### TODO
1. [x] 닫을 때도 안으로 들어가는 느낌 애니메이션 추가
2. [x] SideLog 컴포넌트 자체에 닫기 기능 추가(버튼 추가)
3. [x] 480px까지 화면에 꽉차게 만들기
