### ISSUE TITLE
[Task] Refactor directory structure of server 

### ISSUE THREAD

**Issue by soominna** [codestates/studeaming#175]
### TODO
1. [x] controller 폴더 안의 복잡한 파일들을 더 작은 단위로 나누기
2. [ ] 변수 이름에 일관성 부여
3. [ ] 복잡한 sql 쿼리나 재사용 코드 함수화
