### ISSUE TITLE
[Task] Server setting

### ISSUE THREAD

**Issue by soominna** [codestates/studeaming#18]
### TODO
1. [x] 서버 디렉토리 구성(npm init -> router, controller, middleware, functions)
2. [x] 의존성 모듈 설치
3. [x] `/` 'Hello World' 출력
4. [x] 나머지 경로 에러 처리
