### ISSUE TITLE
[Task] StreamerSetting

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#19]
### TODO
1. [x] 제목 입력 인풋
2. [x] 썸네일 업로드 기능
3. [x] ASMR 사운드 선택 기능
4. [x] 스트리밍 시작 버튼
5. [x] 화면 송출 스크린 보여주기
