### ISSUE TITLE
[Task] Studeaming에서 방송시작시 Viewer화면에 데이터 요청

### ISSUE THREAD

**Issue by Deb-neal** [codestates/studeaming#204]
### TODO

1. [ ] StudeamingSetting 에서 방송시작을 하면 썸네일, 방 제목, 유저이름이 DB에 저장
2. [ ] Home페이지에서는 DB에 저장된 데이터를 API요청을 하여 받아온다
3. [ ] 해당 데이터를 기반으로 방송리스트를 띄우고, 썸네일을 클릭했을때 그 해당 방으로 연결이 되어야한다.

** Assignees, Labels, Milestone 설정했나요? **
