### ISSUE TITLE
[Task] ToggleBox

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#24]
### TODO
1. [x] 토글 디자인 및 애니메이션
2. [x] props로 handler를 받아서 onClick을 수행
 - 완료 버튼 onClick 토글 추가 요청
 - 삭제 버튼 onClick 토글 삭제 요청
 - 토글 on & off 로그 요청
3. [x] props로 정보를 받아와 공부 종류, 토글 색상 커스터마이징
