### ISSUE TITLE
[Task] SideLog

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#26]
### TODO
1. [x] 로그아웃 버튼
2. [x] 사진, 닉네임, 소개글 수정 하는 모달창 만들기
3. [x] 토글 추가 및 삭제 함수 생성 및 ToggleBox에 props 전달
4. [x]  토글 On & Off 함수 생성 및 ToggleBox에 props 전달
5. [x] 하나의 토글만 on인 상태로 유지
6. [x] 슬라이드 애니메이션
7. [x] 로그아웃 시 토글 모두 Off 요청 -> 굳이 필요할까? 그래도 일단 구현해 놓음
8. [x] 헤더에서 햄버거 버튼 클릭시 오픈 
9. [x] 사이드 로그 열리고 닫히는 상태 만들기
