### ISSUE TITLE
[Task] Modal

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#29]
### TODO
1. [x] 모달 배경 셋팅
2. [x] 모달 창 크기 변경할 수 있도록 셋팅
3. [x] 모달 배경 클릭하면 close
4. [x] x 버튼 넣기
5. [x] 모달 열고 닫는 action 만들기
6. [x] 모달 상태 전역으로 만들고 reducer 만들기
