### ISSUE TITLE
[Task] Home페이지에서 슬라이드에 나와있는 Example 클릭시 해당 ASMR 페이지로 이동

### ISSUE THREAD

**Issue by Deb-neal** [codestates/studeaming#304]
### TODO

1. [ ] 각각의 Example을 클릭할때마다 해당페이지의 대한 정보, index값이 전달되어야한다.
2. [ ] index값을 비교하여 저장된 sound와 매칭해 해당 sound[index]을 재생시킨다.
3. [ ] background ASMR이 무한재생되게끔 설정한다.

** Assignees, Labels, Milestone 설정했나요? **
