### ISSUE TITLE
[Task] Strudamer, View페이지에서 각각의 방의 해당하는 ASMR 재생

### ISSUE THREAD

**Issue by Deb-neal** [codestates/studeaming#305]
### TODO

1. [ ] Studeamer가 셋팅화면에서 설정한 ASMR이 방 입장시 재생되게끔 설정한다.
2. [ ] 방에 해당 ASMR이 무한재생되게끔 설정한다.
3. [ ] 입장하는 Viewer(유저) 역시 같은 ASMR을 들을수있게 설정한다.

** Assignees, Labels, Milestone 설정했나요? **
