### ISSUE TITLE
[Task] Studeamer 페이지

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#310]
### TODO
1. [x] 디자인 (ASMR 선택 구역 없애기)
2. [x] 스터디머 페이지에서 다른 페이지로 이동하려고 할 때 경고 띄워주기 -> prompt 기능 사용하면 할 수 있는데, react-router-dom v6에서는 지원을 아직 안해줘서 업데이트 되면 기능 추가해야할듯
3. [x] 스트리머 정보 전달 받아오기
4. [x] 배경 검정색으로 바꾸기
5. [x] 오디오 끄고 켜는 기능
6. [x] 스트리밍 종료 버튼 (종료하기 전 확인 과정 거치기, antd popconfirm 참고)
7. [x] 방 제목 변경 기능
