### ISSUE TITLE
[Task] SideLog 비회원 처리

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#350]
### TODO
1. [x] 비회원인 경우 모달 전체 gray 처리
2. [x] 게스트로 로그인 버튼화
3. [x] 로그인했을 때 사용할 수 있는 서비스 안내 문구 간단히 추가
