### ISSUE TITLE
[Task] Landing페이지 완성

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#355]
### TODO
1. [x] 스트리밍 장면, 채팅 올라오는 gif 따기
2. [x] LandingSection2 gif 삽입
3. [x] Mypage 포도농장 적절히 분포되있는 이미지 따기, Daily 모달 이미지 따기
4. [x] LandingSection3 img 삽입
