### ISSUE TITLE
[Task] SideBar

### ISSUE THREAD

**Issue by Gyosic** [codestates/studeaming#48]
### TODO
1. [x] 즐겨찾는 스터디머 조회 및 삭제
2. [x] 비밀번호 수정 및 탈퇴 버튼
 -> 회원 탈퇴 모달
3. [x] 자체 로그인한 사용자만 비밀번호 수정할 수 있도록 할 것
 -> oauth 로그인에 대한 응답을 persist로 저장해두기
4. [ ] (통계  페이지 생성시) 달력 & 통계 탭 (Ad로 빼기)
