### ISSUE TITLE
[Task] Global CSS

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#79]
### TODO
1. [x] styled-component GlobalStyle 설정
2. [x] 색상 및 폰트 결정
3. [x] root 상수 선언
4. [x] rem에 대해 공부
