### ISSUE TITLE
[Task] Email verification page

### ISSUE THREAD

**Issue by yeinMOON** [codestates/studeaming#96]
### TODO
1. [x] 렌더링시 url code 가져와서 verification 요청
2. [x] 렌더링시 로그인 모달 켜두기
3. [x] 로그인했을 때 메인페이지로 라우팅\

<이메일 인증 시나리오>
1. 이메일에서 인증 링크를 누르면 "/auth/:code" 경로로 이동, code는 서버가 부여하는 인증 코드
2. 해당 경로(/auth 이하)에서는 빈 페이지(배경 좀 꾸미고)에 로그인창만 떠있음 (이 경로로 랜딩될 때 useEffect로 signinModal 오픈)
3. 로그인 컴포넌트에서 현재 url을 읽어서 auth로 시작하면 인증 코드를 서버에 전달해 이메일 인증도 시켜주기 (이외 경로에서는 기존과 동일하게 로그인요청만)
